version: '3'

services:
  oracle-db:
    image: postgres:14.1-alpine
    ports:
      - '54320:5432'
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local